{
 "title": "FastAPI Дашборд",
 "tags": [ "prometheus" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Запросов в минуту",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(http_requests_total[1m]))",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Запросы < 100 ms",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(http_request_duration_seconds_bucket{le=\"0.1\"}[1m]) \n/ ignoring (le) increase(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "Использование памяти",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"app\"}",
     "legendFormat": "mem"
    }
   ]
  },
  {
   "title": "Среднее время ответа",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum{job=\"app\",handler!=\"none\"} / http_request_duration_seconds_count",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "GC Rate / 1m",
   "type": "timeseries",
   "description": "GC invocation durations",
   "gridPos": { "h": 9, "w": 10, "x": 9, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(python_gc_collections_total{instance=~\"$instance\",job=~\"$job\"}[1m])) by (instance)",
     "legendFormat": "{{instance}}"
    },
    { "expr": "python_gc_collections_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Использование CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"app\"}[30s])",
     "legendFormat": "cpu"
    }
   ]
  }
 ]
}